# Generated by Django 5.2.5 on 2025-08-30 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Index",
            new_name="IndexPage",
        ),
    ]
