# Generated by Django 5.2.5 on 2025-09-04 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_rename_index_indexpage"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("title", models.CharField(max_length=100)),
                ("icon", models.ImageField(upload_to="category_icons/")),
            ],
            options={
                "verbose_name_plural": "Book Categories",
            },
        ),
        migrations.CreateModel(
            name="CategorySection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("heading", models.CharField(default="Book Category", max_length=100)),
                ("subheading", models.CharField(blank=True, null=True)),
            ],
            options={
                "verbose_name_plural": "Category Sections",
            },
        ),
    ]
