# Generated by Django 5.2.5 on 2025-09-04 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_bookcategory_categorysection"),
    ]

    operations = [
        migrations.CreateModel(
            name="AboutPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("content", models.TextField()),
                ("image", models.ImageField(upload_to="about")),
            ],
        ),
        migrations.AlterField(
            model_name="bookcategory",
            name="title",
            field=models.CharField(max_length=250),
        ),
    ]
