# Generated by Django 5.2.5 on 2025-09-04 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_aboutpage_alter_bookcategory_title"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="aboutpage",
            options={"verbose_name_plural": "About Pages"},
        ),
    ]
